// todo-app-svelte/src/routes/Todolist.svelte
<script>
  let input = "";
  let todos = [];

  const handleSubmit = () => {
    if (input.trim() !== "") {
      todos = [...todos, { id: Date.now(), text: input, completed: false }];
      input = "";
    }
  };

  const handleDelete = (id) => {
    todos = todos.filter((todo) => todo.id !== id);
  };

  const handleToggle = (id) => {
    todos = todos.map((todo) =>
      todo.id === id ? { ...todo, completed: !todo.completed } : todo
    );
  };
</script>

<div class="flex flex-col items-center justify-center h-screen">
  <h1 class="text-3xl font-bold">Todo List</h1>
  <div class="flex mb-4">
    <form on:submit={handleSubmit}>
      <input
        placeholder="Rajouter une liste"
        class="p-2 border rounded"
        bind:value={input}
      />
      <button type="submit" class="p-2 ml-2 text-white bg-green-500 rounded">
        Ajouter
      </button>
    </form>
  </div>
</div>

<div class="bg-neutral-200 h-90">
  <ul class="grid h-full grid-cols-3 gap-4 xl:w-96">
    {#each todos as { id, text, completed }}
      <li key={id} class="p-4 bg-red-300 border-2 border-indigo-600 h-96">
        <input
          type="checkbox"
          bind:checked={completed}
          on:change={() => handleToggle(id)}
        />
        <span>{text}</span>
        <button on:click={() => handleDelete(id)}>Delete</button>
      </li>
    {/each}
  </ul>
</div>

// todo-app-vue/src/components/TodoList.vue
<template>
  <div class="flex flex-col items-center p-4 w-96">
    <h1 class="mb-4 text-3xl font-bold">Todo List</h1>
    <div class="flex mb-4">
      <input
        v-model="newList.name"
        @keyup.enter="addList"
        placeholder="Rajouter une liste"
        class="p-2 border rounded "
      />
      <button @click="addList" class="p-2 ml-2 text-white bg-green-500 rounded">
        Ajouter
      </button>
    </div>

    
    </div>


  <div class="bg-neutral-200">
        <ul class="grid h-full grid-cols-3 gap-4 mt-4 w-60">
          <li
            v-for="(list, index) in lists"
            :key="index"
            class="p-4 bg-green-300 border-2 border-indigo-600 h-96"
          >
            <Todo :listName="list.name" :items="list.items" />


            <div class="flex items-end content-end">


            <button @click="updateItem(index)" class="p-2 mx-2 text-white bg-blue-500 rounded">Modifier</button>
          <button @click="removeList(index)" class="p-2 text-white bg-red-500 rounded">Supprimer</button>
            </div>
            

        </li>
          
        </ul>

    </div>

</template>

<script>
import Todo from "@/components/Todo.vue";

export default {
  components: {
    Todo,
  },
  data() {
    return {
      newList: { name: "", items: [] },
      lists: [],
    };
  },
  methods: {
    addList() {
      if (this.newList.name.trim() !== "") {
        this.lists.push({ ...this.newList });
        this.newList = { name: "", items: [] };
      }
    },
    removeList(index) {
      this.lists.splice(index, 1);
    },
  },
};
</script>

<style scoped>
/* Styles spécifiques au composant ParentComponent */
</style>
